packages:
  - packages/*
  - third_party/material-viewer/packages/*
  - third_party/three.js

allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true

link-workspace-packages: false

onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - sharp

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - tanstack-router-ga4
  - hdrify*
  - yargs-file-commands
  - humanize-units
  - fastify-file-router
  - fastify-http-exceptions
  - bhouston-profiler
  - bhouston-markdown
  - axios-eventsource
  - vite-file-commands
