packages:
  - packages/*
  - third_party/material-viewer/packages/*
  - third_party/three.js

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: true
  sharp: true

link-workspace-packages: false

minimumReleaseAgeExclude:
  - humanize-units
  - yargs-file-commands
  - tanstack-router-ga4
